services:
  - type: web
    name: Konferans
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 wsgi:application
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
        value: your-secret-key
      - key: SESSION_TYPE
        fromDatabase: false
        value: filesystem
      - key: CACHE_TYPE
        fromDatabase: false
        value: SimpleCache
      # - key: REDIS_URL
      #   fromDatabase: false
      #   value: redis://localhost:6379
