services:
  - type: web
    name: konferans
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 app:socketio
    envVars:
      - key: SECRET_KEY
        value: your_secret_key_here
    plan: free
