services:
  - type: web
    name: Konferans
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        fromDatabase: false
        value: your-secret-key
      - key: SESSION_TYPE
        fromDatabase: false
        value: filesystem
      - key: CACHE_TYPE
        fromDatabase: false
        value: RedisCache
      - key: REDIS_URL
        fromDatabase: false
        value: redis://localhost:6379
